#!/usr/bin/env bash
set -euo pipefail

CI_HELPERS_DIR="${CI_HELPERS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
GRADLE_TASK="${GRADLE_TASK:-}"
BUILD_OPTIONS_JSON="${BUILD_OPTIONS_JSON:-[]}"
SIGNING_UNSIGNED_SCOPE="${SIGNING_UNSIGNED_SCOPE:-none}"
CI_BUILD_TYPE="${CI_BUILD_TYPE:-}"
CI_ARTIFACT_TYPE="${CI_ARTIFACT_TYPE:-}"

if [ -z "$GRADLE_TASK" ]; then
  echo "::error::GRADLE_TASK is required."
  exit 1
fi

read_options_json() {
  local json="$1"
  BUILD_OPTIONS_JSON="$json" python3 "$CI_HELPERS_DIR/parse-gradle-options.py" --from-json --format lines
}

has_explicit_unsigned_args() {
  python3 "$CI_HELPERS_DIR/unsigned_gradle_options.py" --has-explicit-unsigned -- "$@"
}

ensure_unsigned_args() {
  ENSURED_GRADLE_ARGS=()
  while IFS= read -r arg; do
    ENSURED_GRADLE_ARGS+=("$arg")
  done < <(python3 "$CI_HELPERS_DIR/unsigned_gradle_options.py" --ensure-unsigned --format lines -- "$@")
}

task_base_name() {
  local task="$1"
  task="${task##*:}"
  printf '%s' "$task"
}

to_lower() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

release_or_aggregate_task() {
  local task base lower build_type_lower artifact_type_lower
  task="$1"
  build_type_lower="$(to_lower "$CI_BUILD_TYPE")"
  artifact_type_lower="$(to_lower "$CI_ARTIFACT_TYPE")"
  base="$(task_base_name "$task")"
  lower="$(to_lower "$base")"

  # Matrix-provided variant metadata is the most accurate signal.
  if [ "$build_type_lower" = "release" ]; then
    return 0
  fi

  # AAB entries generated by this workflow are release bundles.
  if [ "$artifact_type_lower" = "aab" ]; then
    return 0
  fi

  # Direct release variant tasks.
  if [[ "$lower" == *release* ]]; then
    return 0
  fi

  # Aggregate tasks normally include release variants, so protect them up front.
  case "$lower" in
    build|assemble|bundle)
      return 0
      ;;
  esac

  return 1
}

should_start_unsigned() {
  if has_explicit_unsigned_args "${EXTRA_GRADLE_ARGS[@]}"; then
    return 0
  fi

  case "$SIGNING_UNSIGNED_SCOPE" in
    all)
      return 0
      ;;
    release)
      release_or_aggregate_task "$GRADLE_TASK"
      return $?
      ;;
    *)
      return 1
      ;;
  esac
}

looks_like_signing_failure() {
  local log_file="$1"
  python3 - "$log_file" <<'PY'
import re
import sys
from pathlib import Path

text = Path(sys.argv[1]).read_text(encoding="utf-8", errors="ignore")[-200_000:]
patterns = [
    r"(?is)signingconfig",
    r"(?is)signing config",
    r"(?is)storefile",
    r"(?is)store password",
    r"(?is)storepassword",
    r"(?is)keyalias",
    r"(?is)key password",
    r"(?is)keypassword",
    r"(?is)keystore.*(?:not found|missing|incorrect|failed|tampered|password)",
    r"(?is)cannot recover key",
    r"(?is)android_injected_signing",
    r"(?is)no value has been specified.*signing",
    r"(?is)path may not be null or empty.*signing",
]
for pattern in patterns:
    if re.search(pattern, text):
        sys.exit(0)
sys.exit(1)
PY
}

run_gradle_once() {
  local log_file="$1"
  shift
  local args=("$@")

  echo "Running Gradle task: $GRADLE_TASK"
  if [ "${#args[@]}" -gt 0 ]; then
    printf 'Extra Gradle args:'
    printf ' %q' "${args[@]}"
    printf '\n'
  fi

  set +e
  ./gradlew "$GRADLE_TASK" --no-daemon --stacktrace "${args[@]}" 2>&1 | tee "$log_file"
  local status=${PIPESTATUS[0]}
  return "$status"
}

chmod +x ./gradlew
EXTRA_GRADLE_ARGS=()
while IFS= read -r arg; do
  EXTRA_GRADLE_ARGS+=("$arg")
done < <(read_options_json "$BUILD_OPTIONS_JSON")

START_ARGS=("${EXTRA_GRADLE_ARGS[@]}")
UNSIGNED_DIRECT=false
if should_start_unsigned; then
  ensure_unsigned_args "${START_ARGS[@]}"
  START_ARGS=("${ENSURED_GRADLE_ARGS[@]}")
  UNSIGNED_DIRECT=true
fi

if [ "$UNSIGNED_DIRECT" = "true" ] && [ "$SIGNING_UNSIGNED_SCOPE" = "release" ]; then
  echo "Applying -Punsigned for release/aggregate Gradle task: $GRADLE_TASK"
elif [ "$UNSIGNED_DIRECT" = "true" ]; then
  echo "Using explicit unsigned Gradle mode."
elif [ "$SIGNING_UNSIGNED_SCOPE" = "none" ]; then
  echo "Signing policy does not require -Punsigned for Gradle task: $GRADLE_TASK"
else
  echo "Not applying -Punsigned up front for non-release Gradle task: $GRADLE_TASK"
fi

LOG_FILE="$(mktemp)"
set +e
run_gradle_once "$LOG_FILE" "${START_ARGS[@]}"
status=$?
set -e
if [ "$status" -eq 0 ]; then
  rm -f "$LOG_FILE"
  exit 0
fi

if [ "$UNSIGNED_DIRECT" != "true" ] && [ "$SIGNING_UNSIGNED_SCOPE" = "release" ] && looks_like_signing_failure "$LOG_FILE"; then
  echo "::warning::Gradle failed with a signing-related error on non-release task '$GRADLE_TASK'. Retrying once with -Punsigned as a fallback."
  ensure_unsigned_args "${EXTRA_GRADLE_ARGS[@]}"
  RETRY_ARGS=("${ENSURED_GRADLE_ARGS[@]}")
  rm -f "$LOG_FILE"
  RETRY_LOG_FILE="$(mktemp)"
  set +e
  run_gradle_once "$RETRY_LOG_FILE" "${RETRY_ARGS[@]}"
  status=$?
  set -e
  if [ "$status" -eq 0 ]; then
    rm -f "$RETRY_LOG_FILE"
    exit 0
  fi
  rm -f "$RETRY_LOG_FILE"
fi

rm -f "$LOG_FILE"
exit "$status"
